### PR TITLE
side-by-side diff fixes and early buffer flushing

### PR DESCRIPTION
**Pull request by Lekensteyn**
When using `svn log --diff | colordiff`, the output would only show up when `svn log` terminates (e.g. SIGINT). This is very annoying, so I tried to make it flush earlier. At first I thought that a simple `$| = 1` would do the job, but after looking why that did not work it turned out that `colordiff` first reads the full diff into memory and then starts processing.

This is of course very inefficient, so I converted it to use a buffer for initial format detection (and for preprocessing the special sdiff format) and then read lines one-by-one. The sdiff format was broken for certain input (e.g. CVS) and converted tabs when colordiff incorrectly detects a sdiff format.

The "flush early" changes:
0b31b29 Output a colored diff more often
a3d40ed Start processing data before reading input with diffy
6dc87fe Detect earlier that the format is not sdiff

side-by-side fixes:
54c0e2b Make detect_diff_type accept a single line
bd7ee11 Fix detection for sdiff -l (--left-column) format
653b839 Ignore CVS markers, delayed tab expansion for diffy

misc (a test):
f8c698e Add test for svn log --diff format

The commits have been categorised, but some need to be applied in order I committed them.

Please review and merge, I suggest to add my repo as remote if you are uncomfortable with the "large whitespace/color changes" such as 54c0e2b. (read the commit messages please). All tests passed after each commit.

### CODE REVIEW

**Comment by daveewart** [comment]
Just to be clear and consistent in terminology: when you refer to 'sdiff' do you mean output from this command http://linux.about.com/library/cmd/blcmdl1_sdiff.htm ?

**Comment by Lekensteyn** [comment]
I am referring to the sdiff format from [GNU diffutils](http://www.gnu.org/software/diffutils), from `sdiff(1)` (as shipped with diffutils 3.2):

```
   sdiff - side-by-side merge of file differences
```

(actually, this is the same as `diff -y`, I used both terms to refer to the same)

**Comment by daveewart** [comment]
I need some time to assess the nature of the patches, but it looks like you suggest that the buffered approach is required for **sdiff** because it is _interactive_, is that right? And also sdiff uses side-by-side (diffy) diffs and you've found improvements for detecting and highlighting that, is that also right?

**Comment by Lekensteyn** [comment]
The main reason to use buffering is to avoid stalling when the input is not closed yet (`svn log --diff | colordiff`). The patch to add buffering (for all except sdiff) was quite easy, but then I still encountered a stall. It turned out that the output of `svn log --diff` was at first considered a sdiff. So I _had_ to properly implement buffering for sdifff and add a shortcut to exit the detection loop for sdiff (because `svn log --diff` is a unifiied diff, not sdiff).

There are two buffers involved for ease of implementation:
- One buffer containing lines while initially looking for the diff type. When proceeding with colorization, lines will first be popped from this buffer until it is empty (then it will continue reading from pipe/stdin).
- One buffer specific for sdiff (diffy). This buffer is necessary because lines have to be saved for the actual colorization. Lines in this buffer are scanned for diffy specific details. After the diffy loop (which may exit earlier when the diff was not a diffy), the contents of this buffer are placed in the first buffer.

Before these patches, the input needed to be read completely before colorization could start which can also be considered a buffer (not an efficient one though). After the patches, sdiff will stay buffered because it is indeed interactive, but all other diff types will be outputted earlier.

While adding buffering support, I also improved recognition for CVS diffs and side-by-side diffs containing a column marker (`sdiff --left-column`).

**Comment by Lekensteyn** [comment]
New commit that fixes a minor backwards incompatibility (which should never be noticable, but only when using it interactively, i.e. in filter mode without a pipe). Any progress on this?

**Comment by daveewart** [comment]
> Any progress on this?

I just need to find time to look at it; colordiff is very much a "spare time" activity and there's not much time to spare.  While the Pull Requests remain open, I won't forget about it.  Thanks for your contributions :-)

**Comment by Lekensteyn** [comment]
Thanks for merging!

**Pull request merged**
